title: meteor-application-template-react
description: A template for quickly starting Meteor application development
google_analytics:
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions